---
title: "State Profitability EDA"
author: "Hadrien@rstudio.com"
date: "9/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
```

```{r data-prep}
# load policy data
dat <- read_csv("../outputs/data.csv")

# load map data
# source: https://socviz.co/maps.html
library(maps)
us_states <- map_data("state")
head(us_states)


```

```{r visualize, include = TRUE}

# a basic map
p1 <- ggplot(data = us_states,
            mapping = aes(x = long, y = lat,
                          group = group, fill = region))

p1 + geom_polygon(fill = "white", color = "black")

# fill by LR
us_states_lr <- left_join(us_states, dat, by = c("region"= "state")) # join data sets

p2 <- ggplot(data = us_states_lr,
            aes(x = long, y = lat,
                group = group, fill = loss_ratio))


p2 + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) 

# add a fill gradient
(p3 <- ggplot(data = us_states_lr, aes(x = long, y = lat, group = group, fill = loss_ratio)) +
  geom_polygon(color = "gray90", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  scale_fill_gradient2(midpoint = 0.5, high = scales::muted("red"), low = scales::muted("blue") )
)




```

